server:
  host: "127.0.0.1"
  port: 8080

role:
  name: "server_manager"
  #the name value for role can only be server_manager OR server OR devices
  host: "127.0.0.1"
  port: 8081

manager:
  name: "PC Manager"
  refreshInterval: 3000
  #all devices need to have the same refresh rate 

services:
  system:
    enabled: true
    name: "Système"
    icon: "🖥️"

  processes:
    enabled: true
    name: "Processus"
    icon: "⚙️"

  network:
    enabled: true
    name: "Réseau"
    icon: "🌐"

  storage:
    enabled: true
    name: "Stockage"
    icon: "💾"

  apps:
    enabled: true
    name: "Applications"
    icon: "📦"